function getValidAttributes(incomingAttributes, allowedArray){
    let validAttrs = {};
    Object.keys(incomingAttributes)
    .filter(a => allowedArray.includes(a))
    .map(a => {
        validAttrs[a] = incomingAttributes[a]
    })
    return validAttrs;
}

//Generate html page for documentation.
function documentation(config){
    let header = `<h1>Simple API generated by simpleRESTAPI</h1>
    <p>using ${config.dbname} Database in project ${config.projectName}</p>`;

    let content = config.collections.map(c =>
        `<h3>${c.name}</h3>
            <p><strong>Description: </strong>${c.description}</p>
            <h4>Attributes:</h4>
            <ul>${listAttributes(c.attributes)}</ul>
        `
    )

    let routes = `<a href="/routes">Rotas</a>`

    return header + content.join('') + routes;

    function listAttributes(attributes){
        let content = attributes.map(a => 
            `<li>${a}</li>`
        )
        return content.join('')
    }
}

function routes(config){
    let header = `<h1>Simple API generated by simpleRESTAPI</h1>
    <p>using ${config.dbname} Database in project ${config.projectName}</p>
    <h2>API Routes</h2>`;

    let content = config.collections.map(c =>
        `<h3>${c.name}</h3>
            <h5>Routes:</h5>
            <table>
            <tr>
                <th>METHOD</th>
                <th>description</th>
                <th>route</th>
            </tr>            
            <tr>
                <td>POST</td>
                <td>CREATE ${c.name}</td>
                <td>/${c.slug}</td>
            </tr>
            <tr>
                <td>GET</td>
                <td>GET ${c.name} by string params</td>
                <td>/${c.slug}</td>
            </tr>
            <tr>
                <td>GET</td>
                <td>GET ${c.name} by id</td>
                <td>/${c.slug}/:id</td>
            </tr>
            <tr>
                <td>POST</td>
                <td>UPDATE ${c.name} by id</td>
                <td>/${c.slug}/:id</td>
            </tr>
            <tr>
                <td>DELETE</td>
                <td>DELETE ${c.name} by id</td>
                <td>/${c.slug}/:id</td>
            </tr>                
            </table>
        `
    )

    return header + content.join('');    
}

module.exports = {getValidAttributes, documentation, routes};